//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCrudMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int ID { get; set; }
        public int IdUsuario { get; set; }
        public int IdCancion { get; set; }
        public int Puntuacion { get; set; }
    
        public virtual Canciones Canciones { get; set; }
        public virtual Users Users { get; set; }
    }
}
