//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCrudMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Canciones()
        {
            this.Calificacion = new HashSet<Calificacion>();
        }
    
        public int ID { get; set; }
        public string Nombre_Cancion { get; set; }
        public string Artista { get; set; }
        public string Genero { get; set; }
        public int Favorito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacion { get; set; }
    }
}
